name: CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'venatbot'
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'venatbot@protonmail.com'
          GIT_COMMITTER_EMAIL: 'venatbot@protonmail.com'
          GIT_AUTHOR_NAME: 'Venat'
          GIT_COMMITTER_NAME: 'Venat'
        run: yarn ci
      - name: Extract version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: core
  core-image:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: v${{ needs.release.outputs.current-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: venatbot
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.core
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7
          push: true
          tags: ghcr.io/the-convocation/venat:core, ghcr.io/the-convocation/venat:${{ needs.release.outputs.current-version }}-core
  full-image:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: v${{ needs.release.outputs.current-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: venatbot
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.full
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7
          push: true
          tags: ghcr.io/the-convocation/venat:latest, ghcr.io/the-convocation/venat:full, ghcr.io/the-convocation/venat:${{ needs.release.outputs.current-version }}, ghcr.io/the-convocation/venat:${{ needs.release.outputs.current-version }}-full
